// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDI5XtleWxG7OFIt7wciW5AOl666Qf5pQ',
    appId: '1:815383168621:web:df04ea12000d3de29a6164',
    messagingSenderId: '815383168621',
    projectId: 'aurabeast-d5db0',
    authDomain: 'aurabeast-d5db0.firebaseapp.com',
    storageBucket: 'aurabeast-d5db0.firebasestorage.app',
    measurementId: 'G-9LDDYHRM6M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUefSar9GW3kC6sMwYlSsSos4tuzkdH4w',
    appId: '1:815383168621:ios:5ef0981c6b0c59199a6164',
    messagingSenderId: '815383168621',
    projectId: 'aurabeast-d5db0',
    storageBucket: 'aurabeast-d5db0.firebasestorage.app',
    iosBundleId: 'com.example.aurabeast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUefSar9GW3kC6sMwYlSsSos4tuzkdH4w',
    appId: '1:815383168621:ios:5ef0981c6b0c59199a6164',
    messagingSenderId: '815383168621',
    projectId: 'aurabeast-d5db0',
    storageBucket: 'aurabeast-d5db0.firebasestorage.app',
    iosBundleId: 'com.example.aurabeast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDI5XtleWxG7OFIt7wciW5AOl666Qf5pQ',
    appId: '1:815383168621:web:1ec5c90b0251543b9a6164',
    messagingSenderId: '815383168621',
    projectId: 'aurabeast-d5db0',
    authDomain: 'aurabeast-d5db0.firebaseapp.com',
    storageBucket: 'aurabeast-d5db0.firebasestorage.app',
    measurementId: 'G-73NJTB8RRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOm8UtpRwBycjPOXkj6W-eJFfSwGct6-Q',
    appId: '1:815383168621:android:26c20f458492bb8b9a6164',
    messagingSenderId: '815383168621',
    projectId: 'aurabeast-d5db0',
    storageBucket: 'aurabeast-d5db0.firebasestorage.app',
  );
}
